version: 2

sphinx:
  configuration: docs/conf.py

python:
    version: 3.7
    install:
       - requirements: docs/requirements-docs.txt
       - method: pip
         path: .
         extra_requirements:
             - doc
    system_packages: true
